//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3607
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LrcRedirect.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LrcRedirect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Option version=&quot;1&quot;&gt;
        ///	&lt;Ver1&gt;
        ///		&lt;Link&gt;
        ///			&lt;Name mode=&quot;1&quot; islink=&quot;0&quot; link=&quot;http://www.winampcn.com&quot;&gt;譛ｪ謳懃ｴ｢蛻ｰ豁瑚ｯ・/Name&gt;
        ///			&lt;Name mode=&quot;2&quot; islink=&quot;0&quot; link=&quot;http://www.winampcn.com&quot;&gt;豁､豁梧峇譌豁瑚ｯ・/Name&gt;
        ///			&lt;Name mode=&quot;3&quot; islink=&quot;0&quot; link=&quot;http://www.winampcn.com&quot;&gt;豁｣蝨ｨ謳懃ｴ｢豁瑚ｯ・..&lt;/Name&gt;
        ///			&lt;Name mode=&quot;4&quot; islink=&quot;0&quot; link=&quot;http://www.winampcn.com&quot;&gt;$title$&lt;/Name&gt;
        ///
        ///			&lt;Name mode=&quot;5&quot; islink=&quot;1&quot; link=&quot;http://www.winampcn.com/lyricist.asp&quot;&gt;$error$,轤ｹ蜃ｻ荳玖ｽｽ譁ｰ迚域悽蟆晁ｯ戊ｧ｣蜀ｳ髣ｮ鬚・/Name [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string comStr {
            get {
                return ResourceManager.GetString("comStr", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon extension {
            get {
                object obj = ResourceManager.GetObject("extension", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
