/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GomgView.java
 *
 * Created on Aug 17, 2009, 4:40:57 PM
 */
package nsgcc;

import java.awt.*;
import javax.swing.text.*;

/**
 *
 * @author zhangzheng
 */
public class GomgView extends javax.swing.JFrame {

    /** Creates new form GomgView */
    public GomgView(boolean sts) {
        initComponents();
        status = sts;
        haslast = false;
        gps = gomgGUI1.getGraphics();
        logic = (Gomg) PubData.gamenow;
        this.setTitle(logic.getGameName());
        jTextPane1.setText(msglist);
    }

    public void setInfo(String dname, String IP) {
        jLabel2.setText(dname);
        jLabel4.setText(IP);
    }

    public void setStatus(boolean sts) {
        status = sts;
        if (status) {
            jLabel6.setText("等你下子");
        } else {
            jLabel6.setText("等待對方");
        }
    }

    public boolean getStatus() {
        return status;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gomgGUI1 = new nsgcc.GomgGUI();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gomgGUI1.setName("gomgGUI1"); // NOI18N
        gomgGUI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gomgGUI1MouseClicked(evt);
            }
        });
        gomgGUI1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                gomgGUI1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout gomgGUI1Layout = new javax.swing.GroupLayout(gomgGUI1);
        gomgGUI1.setLayout(gomgGUI1Layout);
        gomgGUI1Layout.setHorizontalGroup(
            gomgGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        gomgGUI1Layout.setVerticalGroup(
            gomgGUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nsgcc.NsgccApp.class).getContext().getResourceMap(GomgView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setMnemonic('S');
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setText(resourceMap.getString("jTextPane1.text")); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gomgGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gomgGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Point getPoint(Point in) {
        int x1 = in.x - sx;
        int x3 = (x1 + dist / 2) / dist;
        int x2 = x1 % dist;
        int y1 = in.y - sy;
        int y3 = (y1 + dist / 2) / dist;
        int y2 = y1 % dist;

        if ((x2 > ru && x2 < dist - ru) || (y2 > ru && y2 < dist - ru)) {
            return null;
        }
        if (x3 < 0 || x3 > 18 || y3 < 0 || y3 > 18) {
            return null;
        }
        return new Point(x3, y3);

    }

    public void DrawPoint(Point realp, boolean black) {
        DrawSpeical(realp, black);
        if (haslast) {
            DrawNormal(lastp, lastc);
        }
        lastp = realp;
        lastc = black;
        haslast = true;
    }

    public void DrawNormal(Point realp, boolean black) {
        if (black) {
            gps.setColor(Color.BLACK);
        } else {
            gps.setColor(Color.WHITE);
        }
        gps.fillOval(realp.x * dist + sx - halfcl, realp.y * dist + sy - halfcl, circle, circle); //Last

    }

    public void DrawSpeical(Point realp, boolean black) {
        gps.setColor(Color.RED);
        gps.fillOval(realp.x * dist + sx - halfcl, realp.y * dist + sy - halfcl, circle, circle); //fill
        if (black) {
            gps.setColor(Color.BLACK);
        } else {
            gps.setColor(Color.WHITE);
        }
        gps.fillOval(realp.x * dist + sx - halfcl + 2, realp.y * dist + sy - halfcl + 2, circle - 4, circle - 4); //Red line
    }

    public void Redraw() {
        int[][] mp = logic.getMap();
        for (int y = 0; y < 19; y++) {
            for (int x = 0; x < 19; x++) {
                if (mp[y][x] != 0) {
                    DrawNormal(new Point(x, y), (mp[y][x] > 0));
                }
            }
        }
        if (haslast) {
            DrawSpeical(lastp, lastc);
        }
    }

    public void ReceiveMsg(String msg) {
        //sEtDocs(logic.dname + ":", Color.RED, true, 16);
        sEtDocs(logic.dname + ":" + msg, Color.RED, false, 14);
        Point p = new Point();
        p.setLocation(0, this.jTextPane1.getHeight());
        jScrollPane1.getViewport().setViewPosition(p);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Redraw();
    }

    public void repaint(Graphics g) {
        super.repaint();
    }

    private void Send() {
        //sEtDocs(PubData.getMyName() + ":", Color.BLUE, true, 16);
        sEtDocs(PubData.getMyName() + ":" + jTextField1.getText(), Color.BLUE, false, 14);
        Point p = new Point();
        p.setLocation(0, this.jTextPane1.getHeight());
        jScrollPane1.getViewport().setViewPosition(p);
        logic.SendMsg(jTextField1.getText());
        jTextField1.setText("");
    }

    public void iNsert(String STR, AttributeSet ATTRSET) {
        Document DOC = jTextPane1.getDocument();
        STR = "\n" + STR;
        try {
            DOC.insertString(DOC.getLength(), STR, ATTRSET);
        } catch (Exception x) {
            x.printStackTrace();
        }
    }

    public void sEtDocs(String STR, Color COL, boolean BOLD, int FONTSIZE) {
        SimpleAttributeSet ATTRSET = new SimpleAttributeSet();
        StyleConstants.setForeground(ATTRSET, COL);
        if (BOLD) {
            StyleConstants.setBold(ATTRSET, true);
        }
        StyleConstants.setFontSize(ATTRSET, FONTSIZE);
        iNsert(STR, ATTRSET);
    }

    private void gomgGUI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gomgGUI1MouseClicked
        // TODO add your handling code here:
        if (!status) {
            return;
        }

        Point tmp = getPoint(evt.getPoint());
        if (tmp == null) {
            return;
        }

        if (logic.TakeKey(tmp)) {
            DrawPoint(tmp, logic.ImBlack());
        }
    }//GEN-LAST:event_gomgGUI1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        logic.EndGame();
    }//GEN-LAST:event_jButton1MouseClicked

    private void gomgGUI1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_gomgGUI1ComponentShown
    }//GEN-LAST:event_gomgGUI1ComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        logic.EndGame();
    }//GEN-LAST:event_formWindowClosing

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Send();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        Send();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (!status && haslast) {
            logic.QuestReturn();
            javax.swing.JOptionPane.showMessageDialog(gomgGUI1, "申请已发送。");
        }
    }//GEN-LAST:event_jButton2MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nsgcc.GomgGUI gomgGUI1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    private boolean status;
    private Graphics gps;
    final int sx = 18;
    final int sy = 18;
    final int dist = 32;
    final int ru = 5;
    final int circle = 28;
    final int halfcl = 14;
    final int maxline = 19;
    public Point lastp;
    boolean lastc;
    public boolean haslast;
    Gomg logic;
    String msglist = "[开始游戏]";
}
