/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GomgGUI.java
 *
 * Created on Aug 17, 2009, 3:52:14 PM
 */
package nsgcc;

import java.awt.*;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author zhangzheng
 */
public class GomgGUI extends javax.swing.JPanel {

    /** Creates new form GomgGUI */
    public GomgGUI() {
        initComponents();
        setOpaque(false);
        ResourceMap rmp = org.jdesktop.application.Application.getInstance(nsgcc.NsgccApp.class).getContext().getResourceMap(GomgGUI.class);
        _img = (rmp.getImageIcon("bg.icon")).getImage();
        this.setName("NAME");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(612, 612));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(_img, 0, 0, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Image _img;
}
