/*
 * NsgccView.java
 */
package nsgcc;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.net.*;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class NsgccView extends FrameView {

    public NsgccView(SingleFrameApplication app) {
        super(app);

        initComponents();

        this.getFrame().setTitle("LanGame");

        jList1.setListData(PubData.inList);
        jComboBox1.setEditable(false);
        try {
            PubData.myAddr = InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException ex) {
            Logger.getLogger(NsgccView.class.getName()).log(Level.SEVERE, null, ex);
        }

        PubData.setCallBack(new CallBack() {

            public void execute() {
                jList1.updateUI();
            }
        });

        String tmp = JOptionPane.showInputDialog("昵称:");
        PubData.setMyName(tmp);

        if (!PubData.initPubData()) {
            JOptionPane.showMessageDialog(mainPanel, "游戏初始化失败！", "错误", JOptionPane.INFORMATION_MESSAGE);
        }
        for (int t = 0; t < PubData.gamecount; t++) {
            jComboBox1.addItem(PubData.gmlst[t]);
        }

        Thread stsdaemon = new StatusD();
        stsdaemon.setDaemon(true);
        stsdaemon.start();

        PubData.gamedaemon = new GameD(new SendMethod() {

            public boolean send(byte[] obj) {
                return true;
            }
        });
        PubData.gamedaemon.setDaemon(true);
        PubData.gamedaemon.start();
        //     GomgView tmap = new GomgView();
        //    tmap.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nsgcc.NsgccApp.class).getContext().getResourceMap(NsgccView.class);
        jButton1.setText(resourceMap.getString("btn_exit.text")); // NOI18N
        jButton1.setName("btn_exit"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText(resourceMap.getString("btn_join.text")); // NOI18N
        jButton2.setName("btn_join"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText(resourceMap.getString("btn_refresh.text")); // NOI18N
        jButton3.setName("btn_refresh"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jComboBox1.setName("jComboBox1"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 203, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        PubData.RefreshUser();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int slt = jList1.getSelectedIndex();
        if (slt < 0) {
            return;
        }
        if (PubData.stslst.get(slt) > 0) {
            return;
        }
        try {
            InetAddress iad = InetAddress.getByName(PubData.adlst.get(slt));
            NControl.sendMessageUDP("Come#" + PubData.getMyName() + "#1" + "#" + jComboBox1.getSelectedIndex(), iad, PubData.getpPub(), PubData.getpRcv());
            JOptionPane.showMessageDialog(mainPanel, "邀请已发送。");
        } catch (UnknownHostException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton2MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
